// Generated by `wit-bindgen` 0.24.0. DO NOT EDIT!
#include "alloy.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `alloy`

__attribute__((__import_module__("alloy"), __import_name__("init")))
extern void __wasm_import_alloy_init(uint8_t *, size_t, uint8_t *, size_t);

__attribute__((__import_module__("alloy"), __import_name__("handle-message")))
extern void __wasm_import_alloy_handle_message(uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t, int32_t, uint8_t *, size_t, uint8_t *, size_t, int64_t, uint8_t *);

__attribute__((__import_module__("alloy"), __import_name__("log")))
extern void __wasm_import_alloy_log(uint8_t *, size_t, uint8_t *, size_t);

__attribute__((__import_module__("alloy"), __import_name__("kv-set")))
extern int32_t __wasm_import_alloy_kv_set(uint8_t *, size_t, uint8_t *, size_t);

__attribute__((__import_module__("alloy"), __import_name__("kv-get")))
extern void __wasm_import_alloy_kv_get(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("alloy"), __import_name__("kv-delete")))
extern int32_t __wasm_import_alloy_kv_delete(uint8_t *, size_t);

__attribute__((__import_module__("alloy"), __import_name__("kv-list")))
extern void __wasm_import_alloy_kv_list(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("alloy"), __import_name__("route-message")))
extern void __wasm_import_alloy_route_message(uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t, int32_t, uint8_t *, size_t, uint8_t *, size_t, int64_t);

__attribute__((__import_module__("alloy"), __import_name__("call")))
extern void __wasm_import_alloy_call(uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t, int32_t, uint8_t *, size_t, uint8_t *, size_t, int64_t, uint8_t *);

__attribute__((__import_module__("alloy"), __import_name__("started")))
extern void __wasm_import_alloy_started(void);

__attribute__((__import_module__("alloy"), __import_name__("get-next-message")))
extern void __wasm_import_alloy_get_next_message(uint8_t *);

__attribute__((__import_module__("alloy"), __import_name__("send-response")))
extern void __wasm_import_alloy_send_response(uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t, int32_t, uint8_t *, size_t, uint8_t *, size_t, int64_t);

__attribute__((__import_module__("alloy"), __import_name__("save-state")))
extern void __wasm_import_alloy_save_state(uint8_t *);

__attribute__((__import_module__("alloy"), __import_name__("load-state")))
extern void __wasm_import_alloy_load_state(uint8_t *, size_t);

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void alloy_option_string_free(alloy_option_string_t *ptr) {
  if (ptr->is_some) {
    alloy_string_free(&ptr->val);
  }
}

void alloy_list_u8_free(alloy_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void alloy_message_free(alloy_message_t *ptr) {
  alloy_string_free(&ptr->id);
  alloy_string_free(&ptr->method);
  alloy_string_free(&ptr->sender);
  alloy_option_string_free(&ptr->target);
  alloy_list_u8_free(&ptr->payload);
}

void alloy_tuple2_string_string_free(alloy_tuple2_string_string_t *ptr) {
  alloy_string_free(&ptr->f0);
  alloy_string_free(&ptr->f1);
}

void alloy_list_tuple2_string_string_free(alloy_list_tuple2_string_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    alloy_tuple2_string_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      alloy_tuple2_string_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void alloy_option_list_tuple2_string_string_free(alloy_option_list_tuple2_string_string_t *ptr) {
  if (ptr->is_some) {
    alloy_list_tuple2_string_string_free(&ptr->val);
  }
}

void alloy_capability_free(alloy_capability_t *ptr) {
  alloy_string_free(&ptr->method);
  alloy_string_free(&ptr->description);
  alloy_option_string_free(&ptr->shortcut);
  alloy_option_list_tuple2_string_string_free(&ptr->annotations);
}

void alloy_list_capability_free(alloy_list_capability_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    alloy_capability_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      alloy_capability_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void alloy_option_list_u8_free(alloy_option_list_u8_t *ptr) {
  if (ptr->is_some) {
    alloy_list_u8_free(&ptr->val);
  }
}

void alloy_list_string_free(alloy_list_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    alloy_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      alloy_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void alloy_option_message_free(alloy_option_message_t *ptr) {
  if (ptr->is_some) {
    alloy_message_free(&ptr->val);
  }
}

void alloy_string_set(alloy_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void alloy_string_dup(alloy_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void alloy_string_free(alloy_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void alloy_init(alloy_string_t *id, alloy_list_capability_t *caps) {
  __wasm_import_alloy_init((uint8_t *) (*id).ptr, (*id).len, (uint8_t *) (*caps).ptr, (*caps).len);
}

void alloy_handle_message(alloy_message_t *msg, alloy_message_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[56];
  int32_t option;
  uint8_t * option1;
  size_t option2;
  if (((*msg).target).is_some) {
    const alloy_string_t *payload0 = &((*msg).target).val;
    option = 1;
    option1 = (uint8_t *) (*payload0).ptr;
    option2 = (*payload0).len;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_alloy_handle_message((uint8_t *) ((*msg).id).ptr, ((*msg).id).len, (uint8_t *) ((*msg).method).ptr, ((*msg).method).len, (uint8_t *) ((*msg).sender).ptr, ((*msg).sender).len, option, option1, option2, (uint8_t *) ((*msg).payload).ptr, ((*msg).payload).len, (int64_t) ((*msg).timestamp), ptr);
  alloy_option_string_t option3;
  switch ((int32_t) *((uint8_t*) (ptr + 24))) {
    case 0: {
      option3.is_some = false;
      break;
    }
    case 1: {
      option3.is_some = true;
      option3.val = (alloy_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 28))), (*((size_t*) (ptr + 32))) };
      break;
    }
  }
  *ret = (alloy_message_t) {
    (alloy_string_t) (alloy_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + 4))) },
    (alloy_string_t) (alloy_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) },
    (alloy_string_t) (alloy_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 16))), (*((size_t*) (ptr + 20))) },
    (alloy_option_string_t) option3,
    (alloy_list_u8_t) (alloy_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 36))), (*((size_t*) (ptr + 40))) },
    (uint64_t) (uint64_t) (*((int64_t*) (ptr + 48))),
  };
}

void alloy_log(alloy_string_t *level, alloy_string_t *message) {
  __wasm_import_alloy_log((uint8_t *) (*level).ptr, (*level).len, (uint8_t *) (*message).ptr, (*message).len);
}

bool alloy_kv_set(alloy_string_t *key, alloy_list_u8_t *value) {
  int32_t ret = __wasm_import_alloy_kv_set((uint8_t *) (*key).ptr, (*key).len, (uint8_t *) (*value).ptr, (*value).len);
  return ret;
}

void alloy_kv_get(alloy_string_t *key, alloy_option_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_alloy_kv_get((uint8_t *) (*key).ptr, (*key).len, ptr);
  alloy_option_list_u8_t option;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (alloy_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 4))), (*((size_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = option;
}

bool alloy_kv_delete(alloy_string_t *key) {
  int32_t ret = __wasm_import_alloy_kv_delete((uint8_t *) (*key).ptr, (*key).len);
  return ret;
}

void alloy_kv_list(alloy_string_t *prefix, alloy_list_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_alloy_kv_list((uint8_t *) (*prefix).ptr, (*prefix).len, ptr);
  *ret = (alloy_list_string_t) { (alloy_string_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + 4))) };
}

void alloy_route_message(alloy_message_t *msg) {
  int32_t option;
  uint8_t * option1;
  size_t option2;
  if (((*msg).target).is_some) {
    const alloy_string_t *payload0 = &((*msg).target).val;
    option = 1;
    option1 = (uint8_t *) (*payload0).ptr;
    option2 = (*payload0).len;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
  }
  __wasm_import_alloy_route_message((uint8_t *) ((*msg).id).ptr, ((*msg).id).len, (uint8_t *) ((*msg).method).ptr, ((*msg).method).len, (uint8_t *) ((*msg).sender).ptr, ((*msg).sender).len, option, option1, option2, (uint8_t *) ((*msg).payload).ptr, ((*msg).payload).len, (int64_t) ((*msg).timestamp));
}

void alloy_call(alloy_message_t *msg, alloy_message_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[56];
  int32_t option;
  uint8_t * option1;
  size_t option2;
  if (((*msg).target).is_some) {
    const alloy_string_t *payload0 = &((*msg).target).val;
    option = 1;
    option1 = (uint8_t *) (*payload0).ptr;
    option2 = (*payload0).len;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_alloy_call((uint8_t *) ((*msg).id).ptr, ((*msg).id).len, (uint8_t *) ((*msg).method).ptr, ((*msg).method).len, (uint8_t *) ((*msg).sender).ptr, ((*msg).sender).len, option, option1, option2, (uint8_t *) ((*msg).payload).ptr, ((*msg).payload).len, (int64_t) ((*msg).timestamp), ptr);
  alloy_option_string_t option3;
  switch ((int32_t) *((uint8_t*) (ptr + 24))) {
    case 0: {
      option3.is_some = false;
      break;
    }
    case 1: {
      option3.is_some = true;
      option3.val = (alloy_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 28))), (*((size_t*) (ptr + 32))) };
      break;
    }
  }
  *ret = (alloy_message_t) {
    (alloy_string_t) (alloy_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + 4))) },
    (alloy_string_t) (alloy_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) },
    (alloy_string_t) (alloy_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 16))), (*((size_t*) (ptr + 20))) },
    (alloy_option_string_t) option3,
    (alloy_list_u8_t) (alloy_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 36))), (*((size_t*) (ptr + 40))) },
    (uint64_t) (uint64_t) (*((int64_t*) (ptr + 48))),
  };
}

void alloy_started(void) {
  __wasm_import_alloy_started();
}

void alloy_get_next_message(alloy_option_message_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[64];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_alloy_get_next_message(ptr);
  alloy_option_message_t option0;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      option0.is_some = false;
      break;
    }
    case 1: {
      option0.is_some = true;
      alloy_option_string_t option;
      switch ((int32_t) *((uint8_t*) (ptr + 32))) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = (alloy_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 36))), (*((size_t*) (ptr + 40))) };
          break;
        }
      }

      option0.val = (alloy_message_t) {
        (alloy_string_t) (alloy_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) },
        (alloy_string_t) (alloy_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 16))), (*((size_t*) (ptr + 20))) },
        (alloy_string_t) (alloy_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 24))), (*((size_t*) (ptr + 28))) },
        (alloy_option_string_t) option,
        (alloy_list_u8_t) (alloy_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 44))), (*((size_t*) (ptr + 48))) },
        (uint64_t) (uint64_t) (*((int64_t*) (ptr + 56))),
      };
      break;
    }
  }
  *ret = option0;
}

void alloy_send_response(alloy_message_t *msg) {
  int32_t option;
  uint8_t * option1;
  size_t option2;
  if (((*msg).target).is_some) {
    const alloy_string_t *payload0 = &((*msg).target).val;
    option = 1;
    option1 = (uint8_t *) (*payload0).ptr;
    option2 = (*payload0).len;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
  }
  __wasm_import_alloy_send_response((uint8_t *) ((*msg).id).ptr, ((*msg).id).len, (uint8_t *) ((*msg).method).ptr, ((*msg).method).len, (uint8_t *) ((*msg).sender).ptr, ((*msg).sender).len, option, option1, option2, (uint8_t *) ((*msg).payload).ptr, ((*msg).payload).len, (int64_t) ((*msg).timestamp));
}

void alloy_save_state(alloy_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_alloy_save_state(ptr);
  *ret = (alloy_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + 4))) };
}

void alloy_load_state(alloy_list_u8_t *state) {
  __wasm_import_alloy_load_state((uint8_t *) (*state).ptr, (*state).len);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_alloy(void);
void __component_type_object_force_link_alloy_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_alloy();
}
