// Generated by `wit-bindgen` 0.24.0. DO NOT EDIT!
package alloy

// #include "alloy.h"
// #include <stdlib.h>
import "C"
import "unsafe"
// Import functions from alloy
type AlloyMessage struct {
  Id string
  Method string
  Sender string
  Target Option[string]
  Payload []uint8
  Timestamp uint64
}

type AlloyTuple2StringStringT struct {
  F0 string
  F1 string
}

type AlloyCapability struct {
  Method string
  Description string
  Shortcut Option[string]
  Annotations Option[[]AlloyTuple2StringStringT]
}

type AlloyStatusKind int

const (
AlloyStatusKindRunning AlloyStatusKind = iota
AlloyStatusKindPaused
AlloyStatusKindStopped
AlloyStatusKindCrashed
)

type AlloyStatus struct {
  kind AlloyStatusKind
}

func (n AlloyStatus) Kind() AlloyStatusKind {
  return n.kind
}

func AlloyStatusRunning() AlloyStatus{
  return AlloyStatus{kind: AlloyStatusKindRunning}
}

func AlloyStatusPaused() AlloyStatus{
  return AlloyStatus{kind: AlloyStatusKindPaused}
}

func AlloyStatusStopped() AlloyStatus{
  return AlloyStatus{kind: AlloyStatusKindStopped}
}

func AlloyStatusCrashed() AlloyStatus{
  return AlloyStatus{kind: AlloyStatusKindCrashed}
}

func AlloyInit(id string, caps []AlloyCapability) {
  var lower_id C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_id.ptr = (*uint8)(unsafe.Pointer(C.CString(id)))
  lower_id.len = C.size_t(len(id))
  var lower_caps C.alloy_list_capability_t
  if len(caps) == 0 {
    lower_caps.ptr = nil
    lower_caps.len = 0
  } else {
    var empty_lower_caps C.alloy_capability_t
    lower_caps.ptr = (*C.alloy_capability_t)(C.malloc(C.size_t(len(caps)) * C.size_t(unsafe.Sizeof(empty_lower_caps))))
    lower_caps.len = C.size_t(len(caps))
    for lower_caps_i := range caps {
      lower_caps_ptr := (*C.alloy_capability_t)(unsafe.Pointer(uintptr(unsafe.Pointer(lower_caps.ptr)) +
      uintptr(lower_caps_i)*unsafe.Sizeof(empty_lower_caps)))
      var lower_caps_ptr_value C.alloy_capability_t
      var lower_caps_ptr_value_method C.alloy_string_t

      // use unsafe.Pointer to avoid copy
      lower_caps_ptr_value_method.ptr = (*uint8)(unsafe.Pointer(C.CString(caps[lower_caps_i].Method)))
      lower_caps_ptr_value_method.len = C.size_t(len(caps[lower_caps_i].Method))
      lower_caps_ptr_value.method = lower_caps_ptr_value_method
      var lower_caps_ptr_value_description C.alloy_string_t

      // use unsafe.Pointer to avoid copy
      lower_caps_ptr_value_description.ptr = (*uint8)(unsafe.Pointer(C.CString(caps[lower_caps_i].Description)))
      lower_caps_ptr_value_description.len = C.size_t(len(caps[lower_caps_i].Description))
      lower_caps_ptr_value.description = lower_caps_ptr_value_description
      var lower_caps_ptr_value_shortcut C.alloy_option_string_t
      if caps[lower_caps_i].Shortcut.IsSome() {
        var lower_caps_ptr_value_shortcut_val C.alloy_string_t

        // use unsafe.Pointer to avoid copy
        lower_caps_ptr_value_shortcut_val.ptr = (*uint8)(unsafe.Pointer(C.CString(caps[lower_caps_i].Shortcut.Unwrap())))
        lower_caps_ptr_value_shortcut_val.len = C.size_t(len(caps[lower_caps_i].Shortcut.Unwrap()))
        lower_caps_ptr_value_shortcut.val = lower_caps_ptr_value_shortcut_val
        lower_caps_ptr_value_shortcut.is_some = true
      }
      lower_caps_ptr_value.shortcut = lower_caps_ptr_value_shortcut
      var lower_caps_ptr_value_annotations C.alloy_option_list_tuple2_string_string_t
      if caps[lower_caps_i].Annotations.IsSome() {
        var lower_caps_ptr_value_annotations_val C.alloy_list_tuple2_string_string_t
        if len(caps[lower_caps_i].Annotations.Unwrap()) == 0 {
          lower_caps_ptr_value_annotations_val.ptr = nil
          lower_caps_ptr_value_annotations_val.len = 0
        } else {
          var empty_lower_caps_ptr_value_annotations_val C.alloy_tuple2_string_string_t
          lower_caps_ptr_value_annotations_val.ptr = (*C.alloy_tuple2_string_string_t)(C.malloc(C.size_t(len(caps[lower_caps_i].Annotations.Unwrap())) * C.size_t(unsafe.Sizeof(empty_lower_caps_ptr_value_annotations_val))))
          lower_caps_ptr_value_annotations_val.len = C.size_t(len(caps[lower_caps_i].Annotations.Unwrap()))
          for lower_caps_ptr_value_annotations_val_i := range caps[lower_caps_i].Annotations.Unwrap() {
            lower_caps_ptr_value_annotations_val_ptr := (*C.alloy_tuple2_string_string_t)(unsafe.Pointer(uintptr(unsafe.Pointer(lower_caps_ptr_value_annotations_val.ptr)) +
            uintptr(lower_caps_ptr_value_annotations_val_i)*unsafe.Sizeof(empty_lower_caps_ptr_value_annotations_val)))
            var lower_caps_ptr_value_annotations_val_ptr_value C.alloy_tuple2_string_string_t
            var lower_caps_ptr_value_annotations_val_ptr_value_f0 C.alloy_string_t

            // use unsafe.Pointer to avoid copy
            lower_caps_ptr_value_annotations_val_ptr_value_f0.ptr = (*uint8)(unsafe.Pointer(C.CString(caps[lower_caps_i].Annotations.Unwrap()[lower_caps_ptr_value_annotations_val_i].F0)))
            lower_caps_ptr_value_annotations_val_ptr_value_f0.len = C.size_t(len(caps[lower_caps_i].Annotations.Unwrap()[lower_caps_ptr_value_annotations_val_i].F0))
            lower_caps_ptr_value_annotations_val_ptr_value.f0 = lower_caps_ptr_value_annotations_val_ptr_value_f0
            var lower_caps_ptr_value_annotations_val_ptr_value_f1 C.alloy_string_t

            // use unsafe.Pointer to avoid copy
            lower_caps_ptr_value_annotations_val_ptr_value_f1.ptr = (*uint8)(unsafe.Pointer(C.CString(caps[lower_caps_i].Annotations.Unwrap()[lower_caps_ptr_value_annotations_val_i].F1)))
            lower_caps_ptr_value_annotations_val_ptr_value_f1.len = C.size_t(len(caps[lower_caps_i].Annotations.Unwrap()[lower_caps_ptr_value_annotations_val_i].F1))
            lower_caps_ptr_value_annotations_val_ptr_value.f1 = lower_caps_ptr_value_annotations_val_ptr_value_f1
            *lower_caps_ptr_value_annotations_val_ptr = lower_caps_ptr_value_annotations_val_ptr_value
          }
        }
        lower_caps_ptr_value_annotations.val = lower_caps_ptr_value_annotations_val
        lower_caps_ptr_value_annotations.is_some = true
      }
      lower_caps_ptr_value.annotations = lower_caps_ptr_value_annotations
      *lower_caps_ptr = lower_caps_ptr_value
    }
  }
  C.alloy_init(&lower_id , &lower_caps )
}

func AlloyHandleMessage(msg AlloyMessage) AlloyMessage {
  var lower_msg C.alloy_message_t
  var lower_msg_id C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_msg_id.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Id)))
  lower_msg_id.len = C.size_t(len(msg.Id))
  lower_msg.id = lower_msg_id
  var lower_msg_method C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_msg_method.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Method)))
  lower_msg_method.len = C.size_t(len(msg.Method))
  lower_msg.method = lower_msg_method
  var lower_msg_sender C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_msg_sender.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Sender)))
  lower_msg_sender.len = C.size_t(len(msg.Sender))
  lower_msg.sender = lower_msg_sender
  var lower_msg_target C.alloy_option_string_t
  if msg.Target.IsSome() {
    var lower_msg_target_val C.alloy_string_t

    // use unsafe.Pointer to avoid copy
    lower_msg_target_val.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Target.Unwrap())))
    lower_msg_target_val.len = C.size_t(len(msg.Target.Unwrap()))
    lower_msg_target.val = lower_msg_target_val
    lower_msg_target.is_some = true
  }
  lower_msg.target = lower_msg_target
  var lower_msg_payload C.alloy_list_u8_t
  if len(msg.Payload) == 0 {
    lower_msg_payload.ptr = nil
    lower_msg_payload.len = 0
  } else {
    var empty_lower_msg_payload C.uint8_t
    lower_msg_payload.ptr = (*C.uint8_t)(C.malloc(C.size_t(len(msg.Payload)) * C.size_t(unsafe.Sizeof(empty_lower_msg_payload))))
    lower_msg_payload.len = C.size_t(len(msg.Payload))
    for lower_msg_payload_i := range msg.Payload {
      lower_msg_payload_ptr := (*C.uint8_t)(unsafe.Pointer(uintptr(unsafe.Pointer(lower_msg_payload.ptr)) +
      uintptr(lower_msg_payload_i)*unsafe.Sizeof(empty_lower_msg_payload)))
      lower_msg_payload_ptr_value := C.uint8_t(msg.Payload[lower_msg_payload_i])
      *lower_msg_payload_ptr = lower_msg_payload_ptr_value
    }
  }
  lower_msg.payload = lower_msg_payload
  lower_msg_timestamp := C.uint64_t(msg.Timestamp)
  lower_msg.timestamp = lower_msg_timestamp
  var ret C.alloy_message_t
  C.alloy_handle_message(&lower_msg , &ret )
  var lift_ret AlloyMessage
  var lift_ret_Id string
  lift_ret_Id = C.GoStringN((*C.char)(unsafe.Pointer(ret.id.ptr)), C.int(ret.id.len))
  lift_ret.Id = lift_ret_Id
  var lift_ret_Method string
  lift_ret_Method = C.GoStringN((*C.char)(unsafe.Pointer(ret.method.ptr)), C.int(ret.method.len))
  lift_ret.Method = lift_ret_Method
  var lift_ret_Sender string
  lift_ret_Sender = C.GoStringN((*C.char)(unsafe.Pointer(ret.sender.ptr)), C.int(ret.sender.len))
  lift_ret.Sender = lift_ret_Sender
  var lift_ret_Target Option[string]
  if ret.target.is_some {
    var lift_ret_Target_val string
    lift_ret_Target_val = C.GoStringN((*C.char)(unsafe.Pointer(ret.target.val.ptr)), C.int(ret.target.val.len))
    lift_ret_Target.Set(lift_ret_Target_val)
  } else {
    lift_ret_Target.Unset()
  }
  lift_ret.Target = lift_ret_Target
  var lift_ret_Payload []uint8
  lift_ret_Payload = make([]uint8, ret.payload.len)
  if ret.payload.len > 0 {
    for lift_ret_Payload_i := 0; lift_ret_Payload_i < int(ret.payload.len); lift_ret_Payload_i++ {
      var empty_lift_ret_Payload C.uint8_t
      lift_ret_Payload_ptr := *(*C.uint8_t)(unsafe.Pointer(uintptr(unsafe.Pointer(ret.payload.ptr)) +
      uintptr(lift_ret_Payload_i)*unsafe.Sizeof(empty_lift_ret_Payload)))
      var list_lift_ret_Payload uint8
      list_lift_ret_Payload = uint8(lift_ret_Payload_ptr)
      lift_ret_Payload[lift_ret_Payload_i] = list_lift_ret_Payload
    }
  }
  lift_ret.Payload = lift_ret_Payload
  var lift_ret_Timestamp uint64
  lift_ret_Timestamp = uint64(ret.timestamp)
  lift_ret.Timestamp = lift_ret_Timestamp
  return lift_ret
}

func AlloyLog(level string, message string) {
  var lower_level C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_level.ptr = (*uint8)(unsafe.Pointer(C.CString(level)))
  lower_level.len = C.size_t(len(level))
  var lower_message C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_message.ptr = (*uint8)(unsafe.Pointer(C.CString(message)))
  lower_message.len = C.size_t(len(message))
  C.alloy_log(&lower_level , &lower_message )
}

func AlloyKvSet(key string, value []uint8) bool {
  var lower_key C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_key.ptr = (*uint8)(unsafe.Pointer(C.CString(key)))
  lower_key.len = C.size_t(len(key))
  var lower_value C.alloy_list_u8_t
  if len(value) == 0 {
    lower_value.ptr = nil
    lower_value.len = 0
  } else {
    var empty_lower_value C.uint8_t
    lower_value.ptr = (*C.uint8_t)(C.malloc(C.size_t(len(value)) * C.size_t(unsafe.Sizeof(empty_lower_value))))
    lower_value.len = C.size_t(len(value))
    for lower_value_i := range value {
      lower_value_ptr := (*C.uint8_t)(unsafe.Pointer(uintptr(unsafe.Pointer(lower_value.ptr)) +
      uintptr(lower_value_i)*unsafe.Sizeof(empty_lower_value)))
      lower_value_ptr_value := C.uint8_t(value[lower_value_i])
      *lower_value_ptr = lower_value_ptr_value
    }
  }
  ret := C.alloy_kv_set(&lower_key , &lower_value )
  lift_ret := ret
  return lift_ret
}

func AlloyKvGet(key string) Option[[]uint8] {
  var lower_key C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_key.ptr = (*uint8)(unsafe.Pointer(C.CString(key)))
  lower_key.len = C.size_t(len(key))
  var ret C.alloy_option_list_u8_t
  C.alloy_kv_get(&lower_key , &ret )
  var lift_ret Option[[]uint8]
  if ret.is_some {
    var lift_ret_val []uint8
    lift_ret_val = make([]uint8, ret.val.len)
    if ret.val.len > 0 {
      for lift_ret_val_i := 0; lift_ret_val_i < int(ret.val.len); lift_ret_val_i++ {
        var empty_lift_ret_val C.uint8_t
        lift_ret_val_ptr := *(*C.uint8_t)(unsafe.Pointer(uintptr(unsafe.Pointer(ret.val.ptr)) +
        uintptr(lift_ret_val_i)*unsafe.Sizeof(empty_lift_ret_val)))
        var list_lift_ret_val uint8
        list_lift_ret_val = uint8(lift_ret_val_ptr)
        lift_ret_val[lift_ret_val_i] = list_lift_ret_val
      }
    }
    lift_ret.Set(lift_ret_val)
  } else {
    lift_ret.Unset()
  }
  return lift_ret
}

func AlloyKvDelete(key string) bool {
  var lower_key C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_key.ptr = (*uint8)(unsafe.Pointer(C.CString(key)))
  lower_key.len = C.size_t(len(key))
  ret := C.alloy_kv_delete(&lower_key )
  lift_ret := ret
  return lift_ret
}

func AlloyKvList(prefix string) []string {
  var lower_prefix C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_prefix.ptr = (*uint8)(unsafe.Pointer(C.CString(prefix)))
  lower_prefix.len = C.size_t(len(prefix))
  var ret C.alloy_list_string_t
  C.alloy_kv_list(&lower_prefix , &ret )
  var lift_ret []string
  lift_ret = make([]string, ret.len)
  if ret.len > 0 {
    for lift_ret_i := 0; lift_ret_i < int(ret.len); lift_ret_i++ {
      var empty_lift_ret C.alloy_string_t
      lift_ret_ptr := *(*C.alloy_string_t)(unsafe.Pointer(uintptr(unsafe.Pointer(ret.ptr)) +
      uintptr(lift_ret_i)*unsafe.Sizeof(empty_lift_ret)))
      var list_lift_ret string
      list_lift_ret = C.GoStringN((*C.char)(unsafe.Pointer(lift_ret_ptr.ptr)), C.int(lift_ret_ptr.len))
      lift_ret[lift_ret_i] = list_lift_ret
    }
  }
  return lift_ret
}

func AlloyRouteMessage(msg AlloyMessage) {
  var lower_msg C.alloy_message_t
  var lower_msg_id C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_msg_id.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Id)))
  lower_msg_id.len = C.size_t(len(msg.Id))
  lower_msg.id = lower_msg_id
  var lower_msg_method C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_msg_method.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Method)))
  lower_msg_method.len = C.size_t(len(msg.Method))
  lower_msg.method = lower_msg_method
  var lower_msg_sender C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_msg_sender.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Sender)))
  lower_msg_sender.len = C.size_t(len(msg.Sender))
  lower_msg.sender = lower_msg_sender
  var lower_msg_target C.alloy_option_string_t
  if msg.Target.IsSome() {
    var lower_msg_target_val C.alloy_string_t

    // use unsafe.Pointer to avoid copy
    lower_msg_target_val.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Target.Unwrap())))
    lower_msg_target_val.len = C.size_t(len(msg.Target.Unwrap()))
    lower_msg_target.val = lower_msg_target_val
    lower_msg_target.is_some = true
  }
  lower_msg.target = lower_msg_target
  var lower_msg_payload C.alloy_list_u8_t
  if len(msg.Payload) == 0 {
    lower_msg_payload.ptr = nil
    lower_msg_payload.len = 0
  } else {
    var empty_lower_msg_payload C.uint8_t
    lower_msg_payload.ptr = (*C.uint8_t)(C.malloc(C.size_t(len(msg.Payload)) * C.size_t(unsafe.Sizeof(empty_lower_msg_payload))))
    lower_msg_payload.len = C.size_t(len(msg.Payload))
    for lower_msg_payload_i := range msg.Payload {
      lower_msg_payload_ptr := (*C.uint8_t)(unsafe.Pointer(uintptr(unsafe.Pointer(lower_msg_payload.ptr)) +
      uintptr(lower_msg_payload_i)*unsafe.Sizeof(empty_lower_msg_payload)))
      lower_msg_payload_ptr_value := C.uint8_t(msg.Payload[lower_msg_payload_i])
      *lower_msg_payload_ptr = lower_msg_payload_ptr_value
    }
  }
  lower_msg.payload = lower_msg_payload
  lower_msg_timestamp := C.uint64_t(msg.Timestamp)
  lower_msg.timestamp = lower_msg_timestamp
  C.alloy_route_message(&lower_msg )
}

func AlloyCall(msg AlloyMessage) AlloyMessage {
  var lower_msg C.alloy_message_t
  var lower_msg_id C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_msg_id.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Id)))
  lower_msg_id.len = C.size_t(len(msg.Id))
  lower_msg.id = lower_msg_id
  var lower_msg_method C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_msg_method.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Method)))
  lower_msg_method.len = C.size_t(len(msg.Method))
  lower_msg.method = lower_msg_method
  var lower_msg_sender C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_msg_sender.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Sender)))
  lower_msg_sender.len = C.size_t(len(msg.Sender))
  lower_msg.sender = lower_msg_sender
  var lower_msg_target C.alloy_option_string_t
  if msg.Target.IsSome() {
    var lower_msg_target_val C.alloy_string_t

    // use unsafe.Pointer to avoid copy
    lower_msg_target_val.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Target.Unwrap())))
    lower_msg_target_val.len = C.size_t(len(msg.Target.Unwrap()))
    lower_msg_target.val = lower_msg_target_val
    lower_msg_target.is_some = true
  }
  lower_msg.target = lower_msg_target
  var lower_msg_payload C.alloy_list_u8_t
  if len(msg.Payload) == 0 {
    lower_msg_payload.ptr = nil
    lower_msg_payload.len = 0
  } else {
    var empty_lower_msg_payload C.uint8_t
    lower_msg_payload.ptr = (*C.uint8_t)(C.malloc(C.size_t(len(msg.Payload)) * C.size_t(unsafe.Sizeof(empty_lower_msg_payload))))
    lower_msg_payload.len = C.size_t(len(msg.Payload))
    for lower_msg_payload_i := range msg.Payload {
      lower_msg_payload_ptr := (*C.uint8_t)(unsafe.Pointer(uintptr(unsafe.Pointer(lower_msg_payload.ptr)) +
      uintptr(lower_msg_payload_i)*unsafe.Sizeof(empty_lower_msg_payload)))
      lower_msg_payload_ptr_value := C.uint8_t(msg.Payload[lower_msg_payload_i])
      *lower_msg_payload_ptr = lower_msg_payload_ptr_value
    }
  }
  lower_msg.payload = lower_msg_payload
  lower_msg_timestamp := C.uint64_t(msg.Timestamp)
  lower_msg.timestamp = lower_msg_timestamp
  var ret C.alloy_message_t
  C.alloy_call(&lower_msg , &ret )
  var lift_ret AlloyMessage
  var lift_ret_Id string
  lift_ret_Id = C.GoStringN((*C.char)(unsafe.Pointer(ret.id.ptr)), C.int(ret.id.len))
  lift_ret.Id = lift_ret_Id
  var lift_ret_Method string
  lift_ret_Method = C.GoStringN((*C.char)(unsafe.Pointer(ret.method.ptr)), C.int(ret.method.len))
  lift_ret.Method = lift_ret_Method
  var lift_ret_Sender string
  lift_ret_Sender = C.GoStringN((*C.char)(unsafe.Pointer(ret.sender.ptr)), C.int(ret.sender.len))
  lift_ret.Sender = lift_ret_Sender
  var lift_ret_Target Option[string]
  if ret.target.is_some {
    var lift_ret_Target_val string
    lift_ret_Target_val = C.GoStringN((*C.char)(unsafe.Pointer(ret.target.val.ptr)), C.int(ret.target.val.len))
    lift_ret_Target.Set(lift_ret_Target_val)
  } else {
    lift_ret_Target.Unset()
  }
  lift_ret.Target = lift_ret_Target
  var lift_ret_Payload []uint8
  lift_ret_Payload = make([]uint8, ret.payload.len)
  if ret.payload.len > 0 {
    for lift_ret_Payload_i := 0; lift_ret_Payload_i < int(ret.payload.len); lift_ret_Payload_i++ {
      var empty_lift_ret_Payload C.uint8_t
      lift_ret_Payload_ptr := *(*C.uint8_t)(unsafe.Pointer(uintptr(unsafe.Pointer(ret.payload.ptr)) +
      uintptr(lift_ret_Payload_i)*unsafe.Sizeof(empty_lift_ret_Payload)))
      var list_lift_ret_Payload uint8
      list_lift_ret_Payload = uint8(lift_ret_Payload_ptr)
      lift_ret_Payload[lift_ret_Payload_i] = list_lift_ret_Payload
    }
  }
  lift_ret.Payload = lift_ret_Payload
  var lift_ret_Timestamp uint64
  lift_ret_Timestamp = uint64(ret.timestamp)
  lift_ret.Timestamp = lift_ret_Timestamp
  return lift_ret
}

func AlloyStarted() {
  C.alloy_started()
}

func AlloyGetNextMessage() Option[AlloyMessage] {
  var ret C.alloy_option_message_t
  C.alloy_get_next_message(&ret )
  var lift_ret Option[AlloyMessage]
  if ret.is_some {
    var lift_ret_val AlloyMessage
    var lift_ret_val_Id string
    lift_ret_val_Id = C.GoStringN((*C.char)(unsafe.Pointer(ret.val.id.ptr)), C.int(ret.val.id.len))
    lift_ret_val.Id = lift_ret_val_Id
    var lift_ret_val_Method string
    lift_ret_val_Method = C.GoStringN((*C.char)(unsafe.Pointer(ret.val.method.ptr)), C.int(ret.val.method.len))
    lift_ret_val.Method = lift_ret_val_Method
    var lift_ret_val_Sender string
    lift_ret_val_Sender = C.GoStringN((*C.char)(unsafe.Pointer(ret.val.sender.ptr)), C.int(ret.val.sender.len))
    lift_ret_val.Sender = lift_ret_val_Sender
    var lift_ret_val_Target Option[string]
    if ret.val.target.is_some {
      var lift_ret_val_Target_val string
      lift_ret_val_Target_val = C.GoStringN((*C.char)(unsafe.Pointer(ret.val.target.val.ptr)), C.int(ret.val.target.val.len))
      lift_ret_val_Target.Set(lift_ret_val_Target_val)
    } else {
      lift_ret_val_Target.Unset()
    }
    lift_ret_val.Target = lift_ret_val_Target
    var lift_ret_val_Payload []uint8
    lift_ret_val_Payload = make([]uint8, ret.val.payload.len)
    if ret.val.payload.len > 0 {
      for lift_ret_val_Payload_i := 0; lift_ret_val_Payload_i < int(ret.val.payload.len); lift_ret_val_Payload_i++ {
        var empty_lift_ret_val_Payload C.uint8_t
        lift_ret_val_Payload_ptr := *(*C.uint8_t)(unsafe.Pointer(uintptr(unsafe.Pointer(ret.val.payload.ptr)) +
        uintptr(lift_ret_val_Payload_i)*unsafe.Sizeof(empty_lift_ret_val_Payload)))
        var list_lift_ret_val_Payload uint8
        list_lift_ret_val_Payload = uint8(lift_ret_val_Payload_ptr)
        lift_ret_val_Payload[lift_ret_val_Payload_i] = list_lift_ret_val_Payload
      }
    }
    lift_ret_val.Payload = lift_ret_val_Payload
    var lift_ret_val_Timestamp uint64
    lift_ret_val_Timestamp = uint64(ret.val.timestamp)
    lift_ret_val.Timestamp = lift_ret_val_Timestamp
    lift_ret.Set(lift_ret_val)
  } else {
    lift_ret.Unset()
  }
  return lift_ret
}

func AlloySendResponse(msg AlloyMessage) {
  var lower_msg C.alloy_message_t
  var lower_msg_id C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_msg_id.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Id)))
  lower_msg_id.len = C.size_t(len(msg.Id))
  lower_msg.id = lower_msg_id
  var lower_msg_method C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_msg_method.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Method)))
  lower_msg_method.len = C.size_t(len(msg.Method))
  lower_msg.method = lower_msg_method
  var lower_msg_sender C.alloy_string_t

  // use unsafe.Pointer to avoid copy
  lower_msg_sender.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Sender)))
  lower_msg_sender.len = C.size_t(len(msg.Sender))
  lower_msg.sender = lower_msg_sender
  var lower_msg_target C.alloy_option_string_t
  if msg.Target.IsSome() {
    var lower_msg_target_val C.alloy_string_t

    // use unsafe.Pointer to avoid copy
    lower_msg_target_val.ptr = (*uint8)(unsafe.Pointer(C.CString(msg.Target.Unwrap())))
    lower_msg_target_val.len = C.size_t(len(msg.Target.Unwrap()))
    lower_msg_target.val = lower_msg_target_val
    lower_msg_target.is_some = true
  }
  lower_msg.target = lower_msg_target
  var lower_msg_payload C.alloy_list_u8_t
  if len(msg.Payload) == 0 {
    lower_msg_payload.ptr = nil
    lower_msg_payload.len = 0
  } else {
    var empty_lower_msg_payload C.uint8_t
    lower_msg_payload.ptr = (*C.uint8_t)(C.malloc(C.size_t(len(msg.Payload)) * C.size_t(unsafe.Sizeof(empty_lower_msg_payload))))
    lower_msg_payload.len = C.size_t(len(msg.Payload))
    for lower_msg_payload_i := range msg.Payload {
      lower_msg_payload_ptr := (*C.uint8_t)(unsafe.Pointer(uintptr(unsafe.Pointer(lower_msg_payload.ptr)) +
      uintptr(lower_msg_payload_i)*unsafe.Sizeof(empty_lower_msg_payload)))
      lower_msg_payload_ptr_value := C.uint8_t(msg.Payload[lower_msg_payload_i])
      *lower_msg_payload_ptr = lower_msg_payload_ptr_value
    }
  }
  lower_msg.payload = lower_msg_payload
  lower_msg_timestamp := C.uint64_t(msg.Timestamp)
  lower_msg.timestamp = lower_msg_timestamp
  C.alloy_send_response(&lower_msg )
}

func AlloySaveState() []uint8 {
  var ret C.alloy_list_u8_t
  C.alloy_save_state(&ret )
  var lift_ret []uint8
  lift_ret = make([]uint8, ret.len)
  if ret.len > 0 {
    for lift_ret_i := 0; lift_ret_i < int(ret.len); lift_ret_i++ {
      var empty_lift_ret C.uint8_t
      lift_ret_ptr := *(*C.uint8_t)(unsafe.Pointer(uintptr(unsafe.Pointer(ret.ptr)) +
      uintptr(lift_ret_i)*unsafe.Sizeof(empty_lift_ret)))
      var list_lift_ret uint8
      list_lift_ret = uint8(lift_ret_ptr)
      lift_ret[lift_ret_i] = list_lift_ret
    }
  }
  return lift_ret
}

func AlloyLoadState(state []uint8) {
  var lower_state C.alloy_list_u8_t
  if len(state) == 0 {
    lower_state.ptr = nil
    lower_state.len = 0
  } else {
    var empty_lower_state C.uint8_t
    lower_state.ptr = (*C.uint8_t)(C.malloc(C.size_t(len(state)) * C.size_t(unsafe.Sizeof(empty_lower_state))))
    lower_state.len = C.size_t(len(state))
    for lower_state_i := range state {
      lower_state_ptr := (*C.uint8_t)(unsafe.Pointer(uintptr(unsafe.Pointer(lower_state.ptr)) +
      uintptr(lower_state_i)*unsafe.Sizeof(empty_lower_state)))
      lower_state_ptr_value := C.uint8_t(state[lower_state_i])
      *lower_state_ptr = lower_state_ptr_value
    }
  }
  C.alloy_load_state(&lower_state )
}

