// Generated by `wit-bindgen` 0.24.0. DO NOT EDIT!
#ifndef __BINDINGS_ALLOY_H
#define __BINDINGS_ALLOY_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>

typedef struct alloy_string_t {
  uint8_t*ptr;
  size_t len;
} alloy_string_t;

typedef struct alloy_option_string_t {
  bool is_some;
  alloy_string_t val;
} alloy_option_string_t;

typedef struct alloy_list_u8_t {
  uint8_t *ptr;
  size_t len;
} alloy_list_u8_t;

// Message structure for plugin communication
typedef struct alloy_message_t {
  alloy_string_t   id;
  alloy_string_t   method;
  alloy_string_t   sender;
  alloy_option_string_t   target;
  alloy_list_u8_t   payload;
  uint64_t   timestamp;
} alloy_message_t;

typedef struct alloy_tuple2_string_string_t {
  alloy_string_t f0;
  alloy_string_t f1;
} alloy_tuple2_string_string_t;

typedef struct alloy_list_tuple2_string_string_t {
  alloy_tuple2_string_string_t *ptr;
  size_t len;
} alloy_list_tuple2_string_string_t;

typedef struct alloy_option_list_tuple2_string_string_t {
  bool is_some;
  alloy_list_tuple2_string_string_t val;
} alloy_option_list_tuple2_string_string_t;

// Capability description for plugin registration
typedef struct alloy_capability_t {
  alloy_string_t   method;
  alloy_string_t   description;
  alloy_option_string_t   shortcut;
  alloy_option_list_tuple2_string_string_t   annotations;
} alloy_capability_t;

// Plugin status
typedef uint8_t alloy_status_t;

#define ALLOY_STATUS_RUNNING 0
#define ALLOY_STATUS_PAUSED 1
#define ALLOY_STATUS_STOPPED 2
#define ALLOY_STATUS_CRASHED 3

typedef struct alloy_list_capability_t {
  alloy_capability_t *ptr;
  size_t len;
} alloy_list_capability_t;

typedef struct alloy_option_list_u8_t {
  bool is_some;
  alloy_list_u8_t val;
} alloy_option_list_u8_t;

typedef struct alloy_list_string_t {
  alloy_string_t *ptr;
  size_t len;
} alloy_list_string_t;

typedef struct alloy_option_message_t {
  bool is_some;
  alloy_message_t val;
} alloy_option_message_t;

// Imported Functions from `alloy`
// Initialize the plugin with its ID and capabilities
extern void alloy_init(alloy_string_t *id, alloy_list_capability_t *caps);
// Handle an incoming message
extern void alloy_handle_message(alloy_message_t *msg, alloy_message_t *ret);
// Log a message to the host
extern void alloy_log(alloy_string_t *level, alloy_string_t *message);
// Key-value storage operations
extern bool alloy_kv_set(alloy_string_t *key, alloy_list_u8_t *value);
extern void alloy_kv_get(alloy_string_t *key, alloy_option_list_u8_t *ret);
extern bool alloy_kv_delete(alloy_string_t *key);
extern void alloy_kv_list(alloy_string_t *prefix, alloy_list_string_t *ret);
// Message routing
extern void alloy_route_message(alloy_message_t *msg);
// Synchronous call to another plugin
extern void alloy_call(alloy_message_t *msg, alloy_message_t *ret);
// Signal that the plugin is ready
extern void alloy_started(void);
// Get the next message (for pull model)
extern void alloy_get_next_message(alloy_option_message_t *ret);
// Send a response
extern void alloy_send_response(alloy_message_t *msg);
// Save plugin state
extern void alloy_save_state(alloy_list_u8_t *ret);
// Load plugin state
extern void alloy_load_state(alloy_list_u8_t *state);

// Helper Functions

void alloy_option_string_free(alloy_option_string_t *ptr);

void alloy_list_u8_free(alloy_list_u8_t *ptr);

void alloy_message_free(alloy_message_t *ptr);

void alloy_tuple2_string_string_free(alloy_tuple2_string_string_t *ptr);

void alloy_list_tuple2_string_string_free(alloy_list_tuple2_string_string_t *ptr);

void alloy_option_list_tuple2_string_string_free(alloy_option_list_tuple2_string_string_t *ptr);

void alloy_capability_free(alloy_capability_t *ptr);

void alloy_list_capability_free(alloy_list_capability_t *ptr);

void alloy_option_list_u8_free(alloy_option_list_u8_t *ptr);

void alloy_list_string_free(alloy_list_string_t *ptr);

void alloy_option_message_free(alloy_option_message_t *ptr);

// Transfers ownership of `s` into the string `ret`
void alloy_string_set(alloy_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void alloy_string_dup(alloy_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void alloy_string_free(alloy_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
