// Generated by `wit-bindgen` 0.24.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod alloy {
  #[used]
  #[doc(hidden)]
  #[cfg(target_arch = "wasm32")]
  static __FORCE_SECTION_REF: fn() = super::__link_custom_section_describing_imports;
  use super::_rt;
  /// Message structure for plugin communication
  #[derive(Clone)]
  pub struct Message {
    pub id: _rt::String,
    pub method: _rt::String,
    pub sender: _rt::String,
    pub target: Option<_rt::String>,
    pub payload: _rt::Vec::<u8>,
    pub timestamp: u64,
  }
  impl ::core::fmt::Debug for Message {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      f.debug_struct("Message").field("id", &self.id).field("method", &self.method).field("sender", &self.sender).field("target", &self.target).field("payload", &self.payload).field("timestamp", &self.timestamp).finish()
    }
  }
  /// Capability description for plugin registration
  #[derive(Clone)]
  pub struct Capability {
    pub method: _rt::String,
    pub description: _rt::String,
    pub shortcut: Option<_rt::String>,
    pub annotations: Option<_rt::Vec::<(_rt::String,_rt::String,)>>,
  }
  impl ::core::fmt::Debug for Capability {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      f.debug_struct("Capability").field("method", &self.method).field("description", &self.description).field("shortcut", &self.shortcut).field("annotations", &self.annotations).finish()
    }
  }
  /// Plugin status
  #[repr(u8)]
  #[derive(Clone, Copy, Eq, PartialEq)]
  pub enum Status {
    Running,
    Paused,
    Stopped,
    Crashed,
  }
  impl ::core::fmt::Debug for Status {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
      match self {
        Status::Running => {
          f.debug_tuple("Status::Running").finish()
        }
        Status::Paused => {
          f.debug_tuple("Status::Paused").finish()
        }
        Status::Stopped => {
          f.debug_tuple("Status::Stopped").finish()
        }
        Status::Crashed => {
          f.debug_tuple("Status::Crashed").finish()
        }
      }
    }
  }

  impl Status{
    pub(crate) unsafe fn _lift(val: u8) -> Status{
      if !cfg!(debug_assertions) {
        return ::core::mem::transmute(val);
      }

      match val {
        0 => Status::Running,
        1 => Status::Paused,
        2 => Status::Stopped,
        3 => Status::Crashed,

        _ => panic!("invalid enum discriminant"),
      }
    }
  }

  #[allow(unused_unsafe, clippy::all)]
  /// Initialize the plugin with its ID and capabilities
  pub fn init(id: &str,caps: &[Capability],){
    unsafe {
      let mut cleanup_list = _rt::Vec::new();
      let vec0 = id;
      let ptr0 = vec0.as_ptr().cast::<u8>();
      let len0 = vec0.len();
      let vec9 = caps;
      let len9 = vec9.len();
      let layout9 = _rt::alloc::Layout::from_size_align_unchecked(vec9.len() * 40, 4);
      let result9 = if layout9.size() != 0 {
        let ptr = _rt::alloc::alloc(layout9).cast::<u8>();
        if ptr.is_null()
        {
          _rt::alloc::handle_alloc_error(layout9);
        }
        ptr
      }else {{
        ::core::ptr::null_mut()
      }};
      for (i, e) in vec9.into_iter().enumerate() {
        let base = result9.add(i * 40);
        {
          let Capability{ method:method1, description:description1, shortcut:shortcut1, annotations:annotations1, } = e;
          let vec2 = method1;
          let ptr2 = vec2.as_ptr().cast::<u8>();
          let len2 = vec2.len();
          *base.add(4).cast::<usize>() = len2;
          *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
          let vec3 = description1;
          let ptr3 = vec3.as_ptr().cast::<u8>();
          let len3 = vec3.len();
          *base.add(12).cast::<usize>() = len3;
          *base.add(8).cast::<*mut u8>() = ptr3.cast_mut();
          match shortcut1 {
            Some(e) => {
              *base.add(16).cast::<u8>() = (1i32) as u8;
              let vec4 = e;
              let ptr4 = vec4.as_ptr().cast::<u8>();
              let len4 = vec4.len();
              *base.add(24).cast::<usize>() = len4;
              *base.add(20).cast::<*mut u8>() = ptr4.cast_mut();
            },
            None => {
              {
                *base.add(16).cast::<u8>() = (0i32) as u8;
              }
            },
          };match annotations1 {
            Some(e) => {
              *base.add(28).cast::<u8>() = (1i32) as u8;
              let vec8 = e;
              let len8 = vec8.len();
              let layout8 = _rt::alloc::Layout::from_size_align_unchecked(vec8.len() * 16, 4);
              let result8 = if layout8.size() != 0 {
                let ptr = _rt::alloc::alloc(layout8).cast::<u8>();
                if ptr.is_null()
                {
                  _rt::alloc::handle_alloc_error(layout8);
                }
                ptr
              }else {{
                ::core::ptr::null_mut()
              }};
              for (i, e) in vec8.into_iter().enumerate() {
                let base = result8.add(i * 16);
                {
                  let (t5_0, t5_1, ) = e;
                  let vec6 = t5_0;
                  let ptr6 = vec6.as_ptr().cast::<u8>();
                  let len6 = vec6.len();
                  *base.add(4).cast::<usize>() = len6;
                  *base.add(0).cast::<*mut u8>() = ptr6.cast_mut();
                  let vec7 = t5_1;
                  let ptr7 = vec7.as_ptr().cast::<u8>();
                  let len7 = vec7.len();
                  *base.add(12).cast::<usize>() = len7;
                  *base.add(8).cast::<*mut u8>() = ptr7.cast_mut();
                }
              }
              *base.add(36).cast::<usize>() = len8;
              *base.add(32).cast::<*mut u8>() = result8;
              cleanup_list.extend_from_slice(&[(result8, layout8),]);
            },
            None => {
              {
                *base.add(28).cast::<u8>() = (0i32) as u8;
              }
            },
          };}
        }

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "init"]
          fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, );
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, ){ unreachable!() }
        wit_import(ptr0.cast_mut(), len0, result9, len9);
        if layout9.size() != 0 {
          _rt::alloc::dealloc(result9.cast(), layout9);
        }
        for (ptr, layout) in cleanup_list {

          if layout.size() != 0 {

            _rt::alloc::dealloc(ptr.cast(), layout);

          }

        }
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// Handle an incoming message
    pub fn handle_message(msg: &Message,) -> Message{
      unsafe {
        #[repr(align(8))]
        struct RetArea([::core::mem::MaybeUninit::<u8>; 56]);
        let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 56]);
        let Message{ id:id0, method:method0, sender:sender0, target:target0, payload:payload0, timestamp:timestamp0, } = msg;
        let vec1 = id0;
        let ptr1 = vec1.as_ptr().cast::<u8>();
        let len1 = vec1.len();
        let vec2 = method0;
        let ptr2 = vec2.as_ptr().cast::<u8>();
        let len2 = vec2.len();
        let vec3 = sender0;
        let ptr3 = vec3.as_ptr().cast::<u8>();
        let len3 = vec3.len();
        let (result5_0,result5_1,result5_2,) = match target0 {
          Some(e) => {
            let vec4 = e;
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();

            (1i32, ptr4.cast_mut(), len4)
          },
          None => {
            (0i32, ::core::ptr::null_mut(), 0usize)
          },
        };let vec6 = payload0;
        let ptr6 = vec6.as_ptr().cast::<u8>();
        let len6 = vec6.len();
        let ptr7 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "handle-message"]
          fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i64, _: *mut u8, );
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i64, _: *mut u8, ){ unreachable!() }
        wit_import(ptr1.cast_mut(), len1, ptr2.cast_mut(), len2, ptr3.cast_mut(), len3, result5_0, result5_1, result5_2, ptr6.cast_mut(), len6, _rt::as_i64(timestamp0), ptr7);
        let l8 = *ptr7.add(0).cast::<*mut u8>();
        let l9 = *ptr7.add(4).cast::<usize>();
        let len10 = l9;
        let bytes10 = _rt::Vec::from_raw_parts(l8.cast(), len10, len10);
        let l11 = *ptr7.add(8).cast::<*mut u8>();
        let l12 = *ptr7.add(12).cast::<usize>();
        let len13 = l12;
        let bytes13 = _rt::Vec::from_raw_parts(l11.cast(), len13, len13);
        let l14 = *ptr7.add(16).cast::<*mut u8>();
        let l15 = *ptr7.add(20).cast::<usize>();
        let len16 = l15;
        let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);
        let l17 = i32::from(*ptr7.add(24).cast::<u8>());
        let l21 = *ptr7.add(36).cast::<*mut u8>();
        let l22 = *ptr7.add(40).cast::<usize>();
        let len23 = l22;
        let l24 = *ptr7.add(48).cast::<i64>();
        Message{
          id: _rt::string_lift(bytes10),
          method: _rt::string_lift(bytes13),
          sender: _rt::string_lift(bytes16),
          target: match l17 {
            0 => None,
            1 => {
              let e = {
                let l18 = *ptr7.add(28).cast::<*mut u8>();
                let l19 = *ptr7.add(32).cast::<usize>();
                let len20 = l19;
                let bytes20 = _rt::Vec::from_raw_parts(l18.cast(), len20, len20);

                _rt::string_lift(bytes20)
              };
              Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          },
          payload: _rt::Vec::from_raw_parts(l21.cast(), len23, len23),
          timestamp: l24 as u64,
        }
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// Log a message to the host
    pub fn log(level: &str,message: &str,){
      unsafe {
        let vec0 = level;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        let vec1 = message;
        let ptr1 = vec1.as_ptr().cast::<u8>();
        let len1 = vec1.len();

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "log"]
          fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, );
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, ){ unreachable!() }
        wit_import(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1);
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// Key-value storage operations
    pub fn kv_set(key: &str,value: &[u8],) -> bool{
      unsafe {
        let vec0 = key;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        let vec1 = value;
        let ptr1 = vec1.as_ptr().cast::<u8>();
        let len1 = vec1.len();

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "kv-set"]
          fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, ) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, ) -> i32{ unreachable!() }
        let ret = wit_import(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1);
        _rt::bool_lift(ret as u8)
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn kv_get(key: &str,) -> Option<_rt::Vec::<u8>>{
      unsafe {
        #[repr(align(4))]
        struct RetArea([::core::mem::MaybeUninit::<u8>; 12]);
        let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 12]);
        let vec0 = key;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "kv-get"]
          fn wit_import(_: *mut u8, _: usize, _: *mut u8, );
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, _: usize, _: *mut u8, ){ unreachable!() }
        wit_import(ptr0.cast_mut(), len0, ptr1);
        let l2 = i32::from(*ptr1.add(0).cast::<u8>());
        match l2 {
          0 => None,
          1 => {
            let e = {
              let l3 = *ptr1.add(4).cast::<*mut u8>();
              let l4 = *ptr1.add(8).cast::<usize>();
              let len5 = l4;

              _rt::Vec::from_raw_parts(l3.cast(), len5, len5)
            };
            Some(e)
          }
          _ => _rt::invalid_enum_discriminant(),
        }
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn kv_delete(key: &str,) -> bool{
      unsafe {
        let vec0 = key;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "kv-delete"]
          fn wit_import(_: *mut u8, _: usize, ) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, _: usize, ) -> i32{ unreachable!() }
        let ret = wit_import(ptr0.cast_mut(), len0);
        _rt::bool_lift(ret as u8)
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn kv_list(prefix: &str,) -> _rt::Vec::<_rt::String>{
      unsafe {
        #[repr(align(4))]
        struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
        let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
        let vec0 = prefix;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "kv-list"]
          fn wit_import(_: *mut u8, _: usize, _: *mut u8, );
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, _: usize, _: *mut u8, ){ unreachable!() }
        wit_import(ptr0.cast_mut(), len0, ptr1);
        let l2 = *ptr1.add(0).cast::<*mut u8>();
        let l3 = *ptr1.add(4).cast::<usize>();
        let base7 = l2;
        let len7 = l3;
        let mut result7 = _rt::Vec::with_capacity(len7);
        for i in 0..len7 {
          let base = base7.add(i * 8);
          let e7 = {
            let l4 = *base.add(0).cast::<*mut u8>();
            let l5 = *base.add(4).cast::<usize>();
            let len6 = l5;
            let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

            _rt::string_lift(bytes6)
          };
          result7.push(e7);
        }
        _rt::cabi_dealloc(base7, len7 * 8, 4);
        result7
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// Message routing
    pub fn route_message(msg: &Message,){
      unsafe {
        let Message{ id:id0, method:method0, sender:sender0, target:target0, payload:payload0, timestamp:timestamp0, } = msg;
        let vec1 = id0;
        let ptr1 = vec1.as_ptr().cast::<u8>();
        let len1 = vec1.len();
        let vec2 = method0;
        let ptr2 = vec2.as_ptr().cast::<u8>();
        let len2 = vec2.len();
        let vec3 = sender0;
        let ptr3 = vec3.as_ptr().cast::<u8>();
        let len3 = vec3.len();
        let (result5_0,result5_1,result5_2,) = match target0 {
          Some(e) => {
            let vec4 = e;
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();

            (1i32, ptr4.cast_mut(), len4)
          },
          None => {
            (0i32, ::core::ptr::null_mut(), 0usize)
          },
        };let vec6 = payload0;
        let ptr6 = vec6.as_ptr().cast::<u8>();
        let len6 = vec6.len();

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "route-message"]
          fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i64, );
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i64, ){ unreachable!() }
        wit_import(ptr1.cast_mut(), len1, ptr2.cast_mut(), len2, ptr3.cast_mut(), len3, result5_0, result5_1, result5_2, ptr6.cast_mut(), len6, _rt::as_i64(timestamp0));
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// Synchronous call to another plugin
    pub fn call(msg: &Message,) -> Message{
      unsafe {
        #[repr(align(8))]
        struct RetArea([::core::mem::MaybeUninit::<u8>; 56]);
        let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 56]);
        let Message{ id:id0, method:method0, sender:sender0, target:target0, payload:payload0, timestamp:timestamp0, } = msg;
        let vec1 = id0;
        let ptr1 = vec1.as_ptr().cast::<u8>();
        let len1 = vec1.len();
        let vec2 = method0;
        let ptr2 = vec2.as_ptr().cast::<u8>();
        let len2 = vec2.len();
        let vec3 = sender0;
        let ptr3 = vec3.as_ptr().cast::<u8>();
        let len3 = vec3.len();
        let (result5_0,result5_1,result5_2,) = match target0 {
          Some(e) => {
            let vec4 = e;
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();

            (1i32, ptr4.cast_mut(), len4)
          },
          None => {
            (0i32, ::core::ptr::null_mut(), 0usize)
          },
        };let vec6 = payload0;
        let ptr6 = vec6.as_ptr().cast::<u8>();
        let len6 = vec6.len();
        let ptr7 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "call"]
          fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i64, _: *mut u8, );
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i64, _: *mut u8, ){ unreachable!() }
        wit_import(ptr1.cast_mut(), len1, ptr2.cast_mut(), len2, ptr3.cast_mut(), len3, result5_0, result5_1, result5_2, ptr6.cast_mut(), len6, _rt::as_i64(timestamp0), ptr7);
        let l8 = *ptr7.add(0).cast::<*mut u8>();
        let l9 = *ptr7.add(4).cast::<usize>();
        let len10 = l9;
        let bytes10 = _rt::Vec::from_raw_parts(l8.cast(), len10, len10);
        let l11 = *ptr7.add(8).cast::<*mut u8>();
        let l12 = *ptr7.add(12).cast::<usize>();
        let len13 = l12;
        let bytes13 = _rt::Vec::from_raw_parts(l11.cast(), len13, len13);
        let l14 = *ptr7.add(16).cast::<*mut u8>();
        let l15 = *ptr7.add(20).cast::<usize>();
        let len16 = l15;
        let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);
        let l17 = i32::from(*ptr7.add(24).cast::<u8>());
        let l21 = *ptr7.add(36).cast::<*mut u8>();
        let l22 = *ptr7.add(40).cast::<usize>();
        let len23 = l22;
        let l24 = *ptr7.add(48).cast::<i64>();
        Message{
          id: _rt::string_lift(bytes10),
          method: _rt::string_lift(bytes13),
          sender: _rt::string_lift(bytes16),
          target: match l17 {
            0 => None,
            1 => {
              let e = {
                let l18 = *ptr7.add(28).cast::<*mut u8>();
                let l19 = *ptr7.add(32).cast::<usize>();
                let len20 = l19;
                let bytes20 = _rt::Vec::from_raw_parts(l18.cast(), len20, len20);

                _rt::string_lift(bytes20)
              };
              Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          },
          payload: _rt::Vec::from_raw_parts(l21.cast(), len23, len23),
          timestamp: l24 as u64,
        }
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// Signal that the plugin is ready
    pub fn started(){
      unsafe {

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "started"]
          fn wit_import();
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(){ unreachable!() }
        wit_import();
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// Get the next message (for pull model)
    pub fn get_next_message() -> Option<Message>{
      unsafe {
        #[repr(align(8))]
        struct RetArea([::core::mem::MaybeUninit::<u8>; 64]);
        let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 64]);
        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "get-next-message"]
          fn wit_import(_: *mut u8, );
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, ){ unreachable!() }
        wit_import(ptr0);
        let l1 = i32::from(*ptr0.add(0).cast::<u8>());
        match l1 {
          0 => None,
          1 => {
            let e = {
              let l2 = *ptr0.add(8).cast::<*mut u8>();
              let l3 = *ptr0.add(12).cast::<usize>();
              let len4 = l3;
              let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
              let l5 = *ptr0.add(16).cast::<*mut u8>();
              let l6 = *ptr0.add(20).cast::<usize>();
              let len7 = l6;
              let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);
              let l8 = *ptr0.add(24).cast::<*mut u8>();
              let l9 = *ptr0.add(28).cast::<usize>();
              let len10 = l9;
              let bytes10 = _rt::Vec::from_raw_parts(l8.cast(), len10, len10);
              let l11 = i32::from(*ptr0.add(32).cast::<u8>());
              let l15 = *ptr0.add(44).cast::<*mut u8>();
              let l16 = *ptr0.add(48).cast::<usize>();
              let len17 = l16;
              let l18 = *ptr0.add(56).cast::<i64>();

              Message{
                id: _rt::string_lift(bytes4),
                method: _rt::string_lift(bytes7),
                sender: _rt::string_lift(bytes10),
                target: match l11 {
                  0 => None,
                  1 => {
                    let e = {
                      let l12 = *ptr0.add(36).cast::<*mut u8>();
                      let l13 = *ptr0.add(40).cast::<usize>();
                      let len14 = l13;
                      let bytes14 = _rt::Vec::from_raw_parts(l12.cast(), len14, len14);

                      _rt::string_lift(bytes14)
                    };
                    Some(e)
                  }
                  _ => _rt::invalid_enum_discriminant(),
                },
                payload: _rt::Vec::from_raw_parts(l15.cast(), len17, len17),
                timestamp: l18 as u64,
              }
            };
            Some(e)
          }
          _ => _rt::invalid_enum_discriminant(),
        }
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// Send a response
    pub fn send_response(msg: &Message,){
      unsafe {
        let Message{ id:id0, method:method0, sender:sender0, target:target0, payload:payload0, timestamp:timestamp0, } = msg;
        let vec1 = id0;
        let ptr1 = vec1.as_ptr().cast::<u8>();
        let len1 = vec1.len();
        let vec2 = method0;
        let ptr2 = vec2.as_ptr().cast::<u8>();
        let len2 = vec2.len();
        let vec3 = sender0;
        let ptr3 = vec3.as_ptr().cast::<u8>();
        let len3 = vec3.len();
        let (result5_0,result5_1,result5_2,) = match target0 {
          Some(e) => {
            let vec4 = e;
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();

            (1i32, ptr4.cast_mut(), len4)
          },
          None => {
            (0i32, ::core::ptr::null_mut(), 0usize)
          },
        };let vec6 = payload0;
        let ptr6 = vec6.as_ptr().cast::<u8>();
        let len6 = vec6.len();

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "send-response"]
          fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i64, );
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i64, ){ unreachable!() }
        wit_import(ptr1.cast_mut(), len1, ptr2.cast_mut(), len2, ptr3.cast_mut(), len3, result5_0, result5_1, result5_2, ptr6.cast_mut(), len6, _rt::as_i64(timestamp0));
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// Save plugin state
    pub fn save_state() -> _rt::Vec::<u8>{
      unsafe {
        #[repr(align(4))]
        struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
        let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "save-state"]
          fn wit_import(_: *mut u8, );
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, ){ unreachable!() }
        wit_import(ptr0);
        let l1 = *ptr0.add(0).cast::<*mut u8>();
        let l2 = *ptr0.add(4).cast::<usize>();
        let len3 = l2;
        _rt::Vec::from_raw_parts(l1.cast(), len3, len3)
      }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// Load plugin state
    pub fn load_state(state: &[u8],){
      unsafe {
        let vec0 = state;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();

        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "alloy")]
        extern "C" {
          #[link_name = "load-state"]
          fn wit_import(_: *mut u8, _: usize, );
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: *mut u8, _: usize, ){ unreachable!() }
        wit_import(ptr0.cast_mut(), len0);
      }
    }

  }

  mod _rt {
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::alloc;

    pub fn as_i64<T: AsI64>(t: T) -> i64 {
      t.as_i64()
    }

    pub trait AsI64 {
      fn as_i64(self) -> i64;
    }

    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
      fn as_i64(self) -> i64 {
        (*self).as_i64()
      }
    }
    
    impl AsI64 for i64 {
      #[inline]
      fn as_i64(self) -> i64 {
        self as i64
      }
    }
    
    impl AsI64 for u64 {
      #[inline]
      fn as_i64(self) -> i64 {
        self as i64
      }
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
      if cfg!(debug_assertions) {
        String::from_utf8(bytes).unwrap()
      } else {
        String::from_utf8_unchecked(bytes)
      }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
      if cfg!(debug_assertions) {
        panic!("invalid enum discriminant")
      } else {
        core::hint::unreachable_unchecked()
      }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
      if cfg!(debug_assertions) {
        match val {
          0 => false,
          1 => true,
          _ => panic!("invalid bool discriminant"),
        }
      } else {
        val != 0
      }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
      if size == 0 {
        return;
      }
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr as *mut u8, layout);
    }
    extern crate alloc as alloc_crate;
  }

  #[cfg(target_arch = "wasm32")]
  #[link_section = "component-type:wit-bindgen:0.24.0:alloy:encoded world"]
  #[doc(hidden)]
  pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 690] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb6\x04\x01A\x02\x01\
A\x02\x01B)\x01ks\x01p}\x01r\x06\x02ids\x06methods\x06senders\x06target\0\x07pay\
load\x01\x09timestampw\x04\0\x07message\x03\0\x02\x01o\x02ss\x01p\x04\x01k\x05\x01\
r\x04\x06methods\x0bdescriptions\x08shortcut\0\x0bannotations\x06\x04\0\x0acapab\
ility\x03\0\x07\x01m\x04\x07running\x06paused\x07stopped\x07crashed\x04\0\x06sta\
tus\x03\0\x09\x01p\x08\x01@\x02\x02ids\x04caps\x0b\x01\0\x04\0\x04init\x01\x0c\x01\
@\x01\x03msg\x03\0\x03\x04\0\x0ehandle-message\x01\x0d\x01@\x02\x05levels\x07mes\
sages\x01\0\x04\0\x03log\x01\x0e\x01@\x02\x03keys\x05value\x01\0\x7f\x04\0\x06kv\
-set\x01\x0f\x01k\x01\x01@\x01\x03keys\0\x10\x04\0\x06kv-get\x01\x11\x01@\x01\x03\
keys\0\x7f\x04\0\x09kv-delete\x01\x12\x01ps\x01@\x01\x06prefixs\0\x13\x04\0\x07k\
v-list\x01\x14\x01@\x01\x03msg\x03\x01\0\x04\0\x0droute-message\x01\x15\x04\0\x04\
call\x01\x0d\x01@\0\x01\0\x04\0\x07started\x01\x16\x01k\x03\x01@\0\0\x17\x04\0\x10\
get-next-message\x01\x18\x04\0\x0dsend-response\x01\x15\x01@\0\0\x01\x04\0\x0asa\
ve-state\x01\x19\x01@\x01\x05state\x01\x01\0\x04\0\x0aload-state\x01\x1a\x03\0\x05\
alloy\x05\0\x04\x01\x0falloy:api/alloy\x04\0\x0b\x0b\x01\0\x05alloy\x03\0\0\0G\x09\
producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.202.0\x10wit-bindgen-rus\
t\x060.24.0";

  #[inline(never)]
  #[doc(hidden)]
  #[cfg(target_arch = "wasm32")]
  pub fn __link_custom_section_describing_imports() {
    wit_bindgen::rt::maybe_link_cabi_realloc();
  }
  
